import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getCurrentUser } from "./firebase/firebase-admin";
import Header from "./components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header userData={JSON.parse(JSON.stringify(currentUser))} />
        {children}
      </body>
    </html>
  );
}
